// Random video game data that is added to Firestore
// After you've signed into GameRate, click the dropdown
// menu in the top right corner and select "Add sample games"

export const randomData = {
  gameNames: [
    "Cyber Legends",
    "Dragon Quest Chronicles",
    "Space Odyssey",
    "Mystic Realms",
    "Battle Arena",
    "Puzzle Master",
    "Racing Thunder",
    "Adventure Quest",
    "Combat Zone",
    "Strategy Wars",
    "Horror Manor",
    "Sports Champion",
    "Platform Hero",
    "Simulation City",
    "Indie Dreams",
    "Fantasy Kingdom",
    "Sci-Fi Explorer",
    "Medieval Knights",
    "Zombie Apocalypse",
    "Magic Academy",
    "Stealth Agent",
    "RPG Legends",
    "Fighting Tournament",
    "Racing Circuit",
    "Puzzle Quest",
    "Adventure Time",
    "Battle Royale",
    "Strategy Empire",
    "Horror Night",
    "Sports League",
    "Platform Jump",
    "Simulation Life",
    "Indie Adventure",
    "Fantasy Quest",
    "Sci-Fi Wars",
    "Medieval Saga",
    "Zombie Hunter",
    "Magic Spells",
    "Stealth Mission",
    "RPG Journey",
    "Fighting Champion",
    "Racing Speed",
    "Puzzle Master",
    "Adventure Hero",
    "Battle Commander",
    "Strategy Tactics",
    "Horror Escape",
    "Sports Victory",
    "Platform Runner",
    "Simulation World",
    "Indie Gem",
  ],
  gamePlatforms: [
    "PC",
    "PlayStation 5",
    "Xbox Series X",
    "Nintendo Switch",
    "PlayStation 4",
    "Xbox One",
    "Steam Deck",
    "Mobile",
    "VR",
    "Retro",
    "Multi-platform",
  ],
  gameGenres: [
    "Action",
    "RPG",
    "Strategy",
    "FPS",
    "Sports",
    "Racing",
    "Puzzle",
    "Adventure",
    "Platformer",
    "Fighting",
    "Simulation",
    "Horror",
    "Indie",
  ],
  gameReviews: [
    { text: "The gameplay was exceptional, absolutely loved it!", rating: 5 },
    { text: "Amazing graphics and smooth controls!", rating: 5 },
    { text: "The story was so engaging and immersive.", rating: 5 },
    { text: "Great multiplayer and friendly community.", rating: 5 },
    { text: "A delightful gaming experience!", rating: 5 },
    {
      text: "Addictive gameplay that kept me playing for hours.",
      rating: 5,
    },
    { text: "Perfectly balanced mechanics and progression.", rating: 5 },
    { text: "Incredible visuals and top-notch sound design.", rating: 5 },
    { text: "Good game with solid mechanics.", rating: 4 },
    { text: "Enjoyed playing it, would recommend.", rating: 4 },
    { text: "Fun gameplay and reasonable price.", rating: 4 },
    { text: "Decent game, but the controls could be better.", rating: 3 },
    { text: "Average experience, nothing extraordinary.", rating: 3 },
    { text: "The gameplay was okay, could be improved.", rating: 3 },
    {
      text: "Loading times were slow, and the gameplay was disappointing.",
      rating: 2,
    },
    { text: "Expected more, but left unsatisfied.", rating: 2 },
    { text: "Underwhelming graphics and repetitive gameplay.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "The game was terrible, will never play again.",
      rating: 1,
    },
    {
      text: "Worst gaming experience I've had so far.",
      rating: 1,
    },
    { text: "Avoid this game, it was unplayable.", rating: 1 },
    { text: "Poor optimization and buggy gameplay.", rating: 1 },
    { text: "Simply outstanding! A gaming masterpiece.", rating: 5 },
    { text: "Couldn't stop playing, amazing game!", rating: 5 },
    { text: "Top-notch quality, worth every penny.", rating: 5 },
    { text: "Highly recommended for gaming enthusiasts.", rating: 5 },
    { text: "Exquisite gameplay that pleased my gaming needs.", rating: 5 },
    { text: "A gem of a game, impeccable in every aspect.", rating: 5 },
    { text: "Excellent variety of gameplay mechanics.", rating: 5 },
    { text: "A fantastic gaming experience overall.", rating: 5 },
    {
      text: "The atmosphere was immersive, perfect for gaming sessions.",
      rating: 4,
    },
    { text: "Good gameplay, but the UI could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the variety of gameplay options.",
      rating: 4,
    },
    { text: "Well-designed levels and engaging mechanics.", rating: 4 },
    { text: "Satisfying gameplay, suitable for casual gaming.", rating: 4 },
    { text: "The gameplay was okay, nothing special.", rating: 3 },
    {
      text: "Controls could be better, but the gameplay was fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the price.", rating: 2 },
    { text: "Mediocre gameplay and lackluster presentation.", rating: 2 },
    {
      text: "Regret spending money on such a disappointing game.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
